(0.004) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.001) SELECT VERSION(); args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.016) SHOW FULL TABLES; args=None
(0.017) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
"GET / HTTP/1.1" 200 5617
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/urls/resolvers.py", line 523, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLPattern '^upload/(?P<path>.*)$'>], [<URLResolver <module 'rest_framework.urls' from '/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/urls.py'> (rest_framework:rest_framework) '^api-auth/'>], [<URLResolver <module 'tasks.urls' from '/Users/cribbee/PycharmProjects/ZoomInDev/apps/tasks/urls.py'> (None:None) '^task'>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^users/$' [name='users-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^users\.(?P<format>[a-z0-9]+)/?$' [name='users-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask/$' [name='usertask-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask\.(?P<format>[a-z0-9]+)/?$' [name='usertask-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask/(?P<tasks_id>[^/.]+)/$' [name='usertask-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask/(?P<tasks_id>[^/.]+)\.(?P<format>[a-z0-9]+)/?$' [name='usertask-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo/$' [name='task-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo\.(?P<format>[a-z0-9]+)/?$' [name='task-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo/(?P<pk>[^/.]+)/$' [name='task-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo/(?P<pk>[^/.]+)\.(?P<format>[a-z0-9]+)/?$' [name='task-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet/$' [name='dataSet-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet\.(?P<format>[a-z0-9]+)/?$' [name='dataSet-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet/(?P<pk>[^/.]+)/$' [name='dataSet-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet/(?P<pk>[^/.]+)\.(?P<format>[a-z0-9]+)/?$' [name='dataSet-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^$' [name='api-root']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^\.(?P<format>[a-z0-9]+)/?$' [name='api-root']>], [<URLResolver <URLPattern list> (api-docs:api-docs) 'docs/'>], [<URLPattern '^api-token-auth/'>], [<URLPattern '^login/'>], [<URLPattern '^task/dataProcessing/drop/' [name='drop']>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'rest_framework.urls' from '/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/urls.py'> (rest_framework:rest_framework) '^api-auth/'>
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/urls/resolvers.py", line 523, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLPattern '^upload/(?P<path>.*)$'>], [<URLResolver <module 'rest_framework.urls' from '/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/urls.py'> (rest_framework:rest_framework) '^api-auth/'>], [<URLResolver <module 'tasks.urls' from '/Users/cribbee/PycharmProjects/ZoomInDev/apps/tasks/urls.py'> (None:None) '^task'>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^users/$' [name='users-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^users\.(?P<format>[a-z0-9]+)/?$' [name='users-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask/$' [name='usertask-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask\.(?P<format>[a-z0-9]+)/?$' [name='usertask-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask/(?P<tasks_id>[^/.]+)/$' [name='usertask-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask/(?P<tasks_id>[^/.]+)\.(?P<format>[a-z0-9]+)/?$' [name='usertask-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo/$' [name='task-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo\.(?P<format>[a-z0-9]+)/?$' [name='task-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo/(?P<pk>[^/.]+)/$' [name='task-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo/(?P<pk>[^/.]+)\.(?P<format>[a-z0-9]+)/?$' [name='task-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet/$' [name='dataSet-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet\.(?P<format>[a-z0-9]+)/?$' [name='dataSet-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet/(?P<pk>[^/.]+)/$' [name='dataSet-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet/(?P<pk>[^/.]+)\.(?P<format>[a-z0-9]+)/?$' [name='dataSet-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^$' [name='api-root']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^\.(?P<format>[a-z0-9]+)/?$' [name='api-root']>], [<URLResolver <URLPattern list> (api-docs:api-docs) 'docs/'>], [<URLPattern '^api-token-auth/'>], [<URLPattern '^login/'>], [<URLPattern '^task/dataProcessing/drop/' [name='drop']>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'tasks.urls' from '/Users/cribbee/PycharmProjects/ZoomInDev/apps/tasks/urls.py'> (None:None) '^task'>
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/urls/resolvers.py", line 523, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLPattern '^upload/(?P<path>.*)$'>], [<URLResolver <module 'rest_framework.urls' from '/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/urls.py'> (rest_framework:rest_framework) '^api-auth/'>], [<URLResolver <module 'tasks.urls' from '/Users/cribbee/PycharmProjects/ZoomInDev/apps/tasks/urls.py'> (None:None) '^task'>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^users/$' [name='users-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^users\.(?P<format>[a-z0-9]+)/?$' [name='users-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask/$' [name='usertask-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask\.(?P<format>[a-z0-9]+)/?$' [name='usertask-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask/(?P<tasks_id>[^/.]+)/$' [name='usertask-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask/(?P<tasks_id>[^/.]+)\.(?P<format>[a-z0-9]+)/?$' [name='usertask-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo/$' [name='task-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo\.(?P<format>[a-z0-9]+)/?$' [name='task-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo/(?P<pk>[^/.]+)/$' [name='task-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo/(?P<pk>[^/.]+)\.(?P<format>[a-z0-9]+)/?$' [name='task-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet/$' [name='dataSet-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet\.(?P<format>[a-z0-9]+)/?$' [name='dataSet-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet/(?P<pk>[^/.]+)/$' [name='dataSet-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet/(?P<pk>[^/.]+)\.(?P<format>[a-z0-9]+)/?$' [name='dataSet-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^$' [name='api-root']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^\.(?P<format>[a-z0-9]+)/?$' [name='api-root']>], [<URLResolver <URLPattern list> (api-docs:api-docs) 'docs/'>], [<URLPattern '^api-token-auth/'>], [<URLPattern '^login/'>], [<URLPattern '^task/dataProcessing/drop/' [name='drop']>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <URLPattern list> (api-docs:api-docs) 'docs/'>
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5901
"GET /docs/ HTTP/1.1" 200 166003
"GET /static/rest_framework/docs/css/base.css HTTP/1.1" 304 0
"GET /static/rest_framework/css/bootstrap-theme.min.css HTTP/1.1" 304 0
"GET /static/rest_framework/css/font-awesome-4.0.3.css HTTP/1.1" 304 0
"GET /static/rest_framework/docs/css/jquery.json-view.min.css HTTP/1.1" 304 0
"GET /docs/schema.js HTTP/1.1" 200 11860
"GET /static/rest_framework/fonts/fontawesome-webfont.woff?v=4.0.3 HTTP/1.1" 304 0
"GET /docs/schema.js HTTP/1.1" 200 11860
(0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.001) SELECT VERSION(); args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.002) SELECT `users_userprofile`.`id`, `users_userprofile`.`password`, `users_userprofile`.`last_login`, `users_userprofile`.`is_superuser`, `users_userprofile`.`username`, `users_userprofile`.`first_name`, `users_userprofile`.`last_name`, `users_userprofile`.`is_staff`, `users_userprofile`.`is_active`, `users_userprofile`.`date_joined`, `users_userprofile`.`name`, `users_userprofile`.`birthday`, `users_userprofile`.`mobile`, `users_userprofile`.`gender`, `users_userprofile`.`email`, `users_userprofile`.`task_num` FROM `users_userprofile` WHERE `users_userprofile`.`username` = 'admin'; args=('admin',)
"POST /login/ HTTP/1.1" 200 176
(0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.000) SELECT VERSION(); args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.000) SELECT `users_userprofile`.`id`, `users_userprofile`.`password`, `users_userprofile`.`last_login`, `users_userprofile`.`is_superuser`, `users_userprofile`.`username`, `users_userprofile`.`first_name`, `users_userprofile`.`last_name`, `users_userprofile`.`is_staff`, `users_userprofile`.`is_active`, `users_userprofile`.`date_joined`, `users_userprofile`.`name`, `users_userprofile`.`birthday`, `users_userprofile`.`mobile`, `users_userprofile`.`gender`, `users_userprofile`.`email`, `users_userprofile`.`task_num` FROM `users_userprofile` WHERE `users_userprofile`.`username` = 'admin'; args=('admin',)
(0.013) SELECT `tasks_taskinfo`.`id`, `tasks_taskinfo`.`user_id`, `tasks_taskinfo`.`task_name`, `tasks_taskinfo`.`data_num`, `tasks_taskinfo`.`status_type`, `tasks_taskinfo`.`add_time`, `tasks_taskinfo`.`task_desc`, `tasks_taskinfo`.`task_home`, `tasks_taskinfo`.`task_folder` FROM `tasks_taskinfo` WHERE `tasks_taskinfo`.`user_id` = 2; args=(2,)
"GET /taskinfo/ HTTP/1.1" 200 151
(0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.000) SELECT VERSION(); args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.000) SELECT `users_userprofile`.`id`, `users_userprofile`.`password`, `users_userprofile`.`last_login`, `users_userprofile`.`is_superuser`, `users_userprofile`.`username`, `users_userprofile`.`first_name`, `users_userprofile`.`last_name`, `users_userprofile`.`is_staff`, `users_userprofile`.`is_active`, `users_userprofile`.`date_joined`, `users_userprofile`.`name`, `users_userprofile`.`birthday`, `users_userprofile`.`mobile`, `users_userprofile`.`gender`, `users_userprofile`.`email`, `users_userprofile`.`task_num` FROM `users_userprofile` WHERE `users_userprofile`.`username` = 'admin'; args=('admin',)
(0.004) SELECT `tasks_dataset`.`id`, `tasks_dataset`.`user_id`, `tasks_dataset`.`task_id`, `tasks_dataset`.`title`, `tasks_dataset`.`desc`, `tasks_dataset`.`x_axis`, `tasks_dataset`.`y_axis`, `tasks_dataset`.`chart_type`, `tasks_dataset`.`step1`, `tasks_dataset`.`step2`, `tasks_dataset`.`step3`, `tasks_dataset`.`step4`, `tasks_dataset`.`step5`, `tasks_dataset`.`add_time` FROM `tasks_dataset` WHERE `tasks_dataset`.`user_id` = 2; args=(2,)
"GET /dataSet/ HTTP/1.1" 200 1282
"GET /docs/ HTTP/1.1" 200 166003
"GET /docs/ HTTP/1.1" 200 166003
"GET /docs/schema.js HTTP/1.1" 200 11860
(0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.000) SELECT VERSION(); args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.000) SELECT `users_userprofile`.`id`, `users_userprofile`.`password`, `users_userprofile`.`last_login`, `users_userprofile`.`is_superuser`, `users_userprofile`.`username`, `users_userprofile`.`first_name`, `users_userprofile`.`last_name`, `users_userprofile`.`is_staff`, `users_userprofile`.`is_active`, `users_userprofile`.`date_joined`, `users_userprofile`.`name`, `users_userprofile`.`birthday`, `users_userprofile`.`mobile`, `users_userprofile`.`gender`, `users_userprofile`.`email`, `users_userprofile`.`task_num` FROM `users_userprofile` WHERE `users_userprofile`.`username` = 'admin'; args=('admin',)
"POST /login/ HTTP/1.1" 200 176
(0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.000) SELECT VERSION(); args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.000) SELECT `users_userprofile`.`id`, `users_userprofile`.`password`, `users_userprofile`.`last_login`, `users_userprofile`.`is_superuser`, `users_userprofile`.`username`, `users_userprofile`.`first_name`, `users_userprofile`.`last_name`, `users_userprofile`.`is_staff`, `users_userprofile`.`is_active`, `users_userprofile`.`date_joined`, `users_userprofile`.`name`, `users_userprofile`.`birthday`, `users_userprofile`.`mobile`, `users_userprofile`.`gender`, `users_userprofile`.`email`, `users_userprofile`.`task_num` FROM `users_userprofile` WHERE `users_userprofile`.`username` = 'admin'; args=('admin',)
(0.000) SELECT `tasks_taskinfo`.`id`, `tasks_taskinfo`.`user_id`, `tasks_taskinfo`.`task_name`, `tasks_taskinfo`.`data_num`, `tasks_taskinfo`.`status_type`, `tasks_taskinfo`.`add_time`, `tasks_taskinfo`.`task_desc`, `tasks_taskinfo`.`task_home`, `tasks_taskinfo`.`task_folder` FROM `tasks_taskinfo` WHERE `tasks_taskinfo`.`user_id` = 2; args=(2,)
"GET /taskinfo/ HTTP/1.1" 200 151
(0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.000) SELECT VERSION(); args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.000) SELECT `users_userprofile`.`id`, `users_userprofile`.`password`, `users_userprofile`.`last_login`, `users_userprofile`.`is_superuser`, `users_userprofile`.`username`, `users_userprofile`.`first_name`, `users_userprofile`.`last_name`, `users_userprofile`.`is_staff`, `users_userprofile`.`is_active`, `users_userprofile`.`date_joined`, `users_userprofile`.`name`, `users_userprofile`.`birthday`, `users_userprofile`.`mobile`, `users_userprofile`.`gender`, `users_userprofile`.`email`, `users_userprofile`.`task_num` FROM `users_userprofile` WHERE `users_userprofile`.`username` = 'admin'; args=('admin',)
(0.001) SELECT `tasks_taskinfo`.`id`, `tasks_taskinfo`.`user_id`, `tasks_taskinfo`.`task_name`, `tasks_taskinfo`.`data_num`, `tasks_taskinfo`.`status_type`, `tasks_taskinfo`.`add_time`, `tasks_taskinfo`.`task_desc`, `tasks_taskinfo`.`task_home`, `tasks_taskinfo`.`task_folder` FROM `tasks_taskinfo` WHERE (`tasks_taskinfo`.`user_id` = 2 AND `tasks_taskinfo`.`id` = 1); args=(2, 1)
"GET /taskinfo/1/ HTTP/1.1" 200 149
(0.002) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.012) SELECT VERSION(); args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.063) SHOW FULL TABLES; args=None
(0.113) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
"GET / HTTP/1.1" 200 5617
"GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
"GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
"GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
"GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
"GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1735
"GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
"GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 37045
"GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121200
"GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 200 86927
"GET /static/rest_framework/js/default.js HTTP/1.1" 200 1262
"GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/urls/resolvers.py", line 523, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLPattern '^upload/(?P<path>.*)$'>], [<URLResolver <module 'rest_framework.urls' from '/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/urls.py'> (rest_framework:rest_framework) '^api-auth/'>], [<URLResolver <module 'tasks.urls' from '/Users/cribbee/PycharmProjects/ZoomInDev/apps/tasks/urls.py'> (None:None) '^task'>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^users/$' [name='users-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^users\.(?P<format>[a-z0-9]+)/?$' [name='users-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask/$' [name='usertask-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask\.(?P<format>[a-z0-9]+)/?$' [name='usertask-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask/(?P<tasks_id>[^/.]+)/$' [name='usertask-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask/(?P<tasks_id>[^/.]+)\.(?P<format>[a-z0-9]+)/?$' [name='usertask-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo/$' [name='task-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo\.(?P<format>[a-z0-9]+)/?$' [name='task-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo/(?P<pk>[^/.]+)/$' [name='task-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo/(?P<pk>[^/.]+)\.(?P<format>[a-z0-9]+)/?$' [name='task-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet/$' [name='dataSet-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet\.(?P<format>[a-z0-9]+)/?$' [name='dataSet-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet/(?P<pk>[^/.]+)/$' [name='dataSet-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet/(?P<pk>[^/.]+)\.(?P<format>[a-z0-9]+)/?$' [name='dataSet-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^$' [name='api-root']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^\.(?P<format>[a-z0-9]+)/?$' [name='api-root']>], [<URLResolver <URLPattern list> (api-docs:api-docs) 'docs/'>], [<URLPattern '^api-token-auth/'>], [<URLPattern '^login/'>], [<URLPattern '^task/dataProcessing/drop/' [name='drop']>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'rest_framework.urls' from '/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/urls.py'> (rest_framework:rest_framework) '^api-auth/'>
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/urls/resolvers.py", line 523, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLPattern '^upload/(?P<path>.*)$'>], [<URLResolver <module 'rest_framework.urls' from '/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/urls.py'> (rest_framework:rest_framework) '^api-auth/'>], [<URLResolver <module 'tasks.urls' from '/Users/cribbee/PycharmProjects/ZoomInDev/apps/tasks/urls.py'> (None:None) '^task'>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^users/$' [name='users-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^users\.(?P<format>[a-z0-9]+)/?$' [name='users-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask/$' [name='usertask-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask\.(?P<format>[a-z0-9]+)/?$' [name='usertask-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask/(?P<tasks_id>[^/.]+)/$' [name='usertask-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask/(?P<tasks_id>[^/.]+)\.(?P<format>[a-z0-9]+)/?$' [name='usertask-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo/$' [name='task-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo\.(?P<format>[a-z0-9]+)/?$' [name='task-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo/(?P<pk>[^/.]+)/$' [name='task-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo/(?P<pk>[^/.]+)\.(?P<format>[a-z0-9]+)/?$' [name='task-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet/$' [name='dataSet-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet\.(?P<format>[a-z0-9]+)/?$' [name='dataSet-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet/(?P<pk>[^/.]+)/$' [name='dataSet-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet/(?P<pk>[^/.]+)\.(?P<format>[a-z0-9]+)/?$' [name='dataSet-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^$' [name='api-root']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^\.(?P<format>[a-z0-9]+)/?$' [name='api-root']>], [<URLResolver <URLPattern list> (api-docs:api-docs) 'docs/'>], [<URLPattern '^api-token-auth/'>], [<URLPattern '^login/'>], [<URLPattern '^task/dataProcessing/drop/' [name='drop']>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'tasks.urls' from '/Users/cribbee/PycharmProjects/ZoomInDev/apps/tasks/urls.py'> (None:None) '^task'>
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/urls/resolvers.py", line 523, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLPattern '^upload/(?P<path>.*)$'>], [<URLResolver <module 'rest_framework.urls' from '/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/urls.py'> (rest_framework:rest_framework) '^api-auth/'>], [<URLResolver <module 'tasks.urls' from '/Users/cribbee/PycharmProjects/ZoomInDev/apps/tasks/urls.py'> (None:None) '^task'>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^users/$' [name='users-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^users\.(?P<format>[a-z0-9]+)/?$' [name='users-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask/$' [name='usertask-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask\.(?P<format>[a-z0-9]+)/?$' [name='usertask-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask/(?P<tasks_id>[^/.]+)/$' [name='usertask-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask/(?P<tasks_id>[^/.]+)\.(?P<format>[a-z0-9]+)/?$' [name='usertask-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo/$' [name='task-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo\.(?P<format>[a-z0-9]+)/?$' [name='task-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo/(?P<pk>[^/.]+)/$' [name='task-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo/(?P<pk>[^/.]+)\.(?P<format>[a-z0-9]+)/?$' [name='task-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet/$' [name='dataSet-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet\.(?P<format>[a-z0-9]+)/?$' [name='dataSet-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet/(?P<pk>[^/.]+)/$' [name='dataSet-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet/(?P<pk>[^/.]+)\.(?P<format>[a-z0-9]+)/?$' [name='dataSet-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^$' [name='api-root']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^\.(?P<format>[a-z0-9]+)/?$' [name='api-root']>], [<URLResolver <URLPattern list> (api-docs:api-docs) 'docs/'>], [<URLPattern '^api-token-auth/'>], [<URLPattern '^login/'>], [<URLPattern '^task/dataProcessing/drop/' [name='drop']>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <URLPattern list> (api-docs:api-docs) 'docs/'>
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5901
Exception while resolving variable 'hide_label' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
KeyError: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [hide_label] in {'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x10b8ad9b0>}
Exception while resolving variable 'placeholder' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
KeyError: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [placeholder] in {'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x10b8ad9b0>}
Exception while resolving variable 'autofocus' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
KeyError: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [autofocus] in {'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x10b8ad9b0>}
Exception while resolving variable 'hide_label' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
KeyError: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [hide_label] in {'base_template': 'input.html', 'input_type': 'password', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x10b8ad9b0>}
Exception while resolving variable 'placeholder' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
KeyError: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [placeholder] in {'base_template': 'input.html', 'input_type': 'password', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x10b8ad9b0>}
Exception while resolving variable 'autofocus' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
KeyError: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [autofocus] in {'base_template': 'input.html', 'input_type': 'password', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x10b8ad9b0>}
"GET /users/ HTTP/1.1" 405 7634
"GET /docs HTTP/1.1" 301 0
"GET /docs/ HTTP/1.1" 200 166003
"GET /static/rest_framework/css/bootstrap-theme.min.css HTTP/1.1" 200 124939
"GET /static/rest_framework/docs/css/jquery.json-view.min.css HTTP/1.1" 200 1307
"GET /static/rest_framework/css/font-awesome-4.0.3.css HTTP/1.1" 200 21658
"GET /static/rest_framework/docs/css/base.css HTTP/1.1" 200 5942
"GET /static/rest_framework/js/coreapi-0.1.1.js HTTP/1.1" 200 157600
"GET /docs/schema.js HTTP/1.1" 200 11860
"GET /static/rest_framework/docs/js/jquery.json-view.min.js HTTP/1.1" 200 2700
"GET /static/rest_framework/docs/js/api.js HTTP/1.1" 200 10539
"GET /static/rest_framework/fonts/fontawesome-webfont.woff?v=4.0.3 HTTP/1.1" 200 44432
"GET /static/rest_framework/docs/img/favicon.ico HTTP/1.1" 200 5430
