(0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.000) SELECT VERSION(); args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.017) SHOW FULL TABLES; args=None
(0.005) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
(0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.000) SELECT VERSION(); args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.009) SHOW FULL TABLES; args=None
(0.003) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
(0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.000) SELECT VERSION(); args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.006) SELECT `users_userprofile`.`id`, `users_userprofile`.`password`, `users_userprofile`.`last_login`, `users_userprofile`.`is_superuser`, `users_userprofile`.`username`, `users_userprofile`.`first_name`, `users_userprofile`.`last_name`, `users_userprofile`.`is_staff`, `users_userprofile`.`is_active`, `users_userprofile`.`date_joined`, `users_userprofile`.`name`, `users_userprofile`.`birthday`, `users_userprofile`.`mobile`, `users_userprofile`.`gender`, `users_userprofile`.`email`, `users_userprofile`.`task_num` FROM `users_userprofile` WHERE `users_userprofile`.`username` = 'admin'; args=('admin',)
(0.005) SELECT `tasks_taskinfo`.`id`, `tasks_taskinfo`.`user_id`, `tasks_taskinfo`.`task_name`, `tasks_taskinfo`.`data_num`, `tasks_taskinfo`.`status_type`, `tasks_taskinfo`.`add_time`, `tasks_taskinfo`.`task_desc`, `tasks_taskinfo`.`task_home`, `tasks_taskinfo`.`task_folder` FROM `tasks_taskinfo` WHERE `tasks_taskinfo`.`id` = 1; args=(1,)
data_set_name is /Users/cribbee/Downloads/1/Data/1251.json
(0.001) SELECT `tasks_taskinfo`.`id`, `tasks_taskinfo`.`user_id`, `tasks_taskinfo`.`task_name`, `tasks_taskinfo`.`data_num`, `tasks_taskinfo`.`status_type`, `tasks_taskinfo`.`add_time`, `tasks_taskinfo`.`task_desc`, `tasks_taskinfo`.`task_home`, `tasks_taskinfo`.`task_folder` FROM `tasks_taskinfo` WHERE `tasks_taskinfo`.`id` = 1; args=(1,)
(0.003) INSERT INTO `tasks_dataset` (`user_id`, `task_id`, `title`, `desc`, `x_axis`, `y_axis`, `chart_type`, `step1`, `step2`, `step3`, `step4`, `step5`, `add_time`) VALUES (2, 1, '', '', '', '', 0, '/Users/cribbee/Downloads/1/Data/1251.json', '/Users/cribbee/Downloads/1/Data/1252.csv', '/Users/cribbee/Downloads/1/Data/1253.csv', '', '', '2018-06-25 08:50:55.530263'); args=[2, 1, '', '', '', '', 0, '/Users/cribbee/Downloads/1/Data/1251.json', '/Users/cribbee/Downloads/1/Data/1252.csv', '/Users/cribbee/Downloads/1/Data/1253.csv', '', '', '2018-06-25 08:50:55.530263']
"POST /dataSet/ HTTP/1.1" 201 164
(0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.000) SELECT VERSION(); args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.014) SHOW FULL TABLES; args=None
(0.004) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
"GET /docs/ HTTP/1.1" 200 127601
"GET /docs/schema.js HTTP/1.1" 200 10556
"GET /static/rest_framework/docs/img/favicon.ico HTTP/1.1" 200 5430
(0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.000) SELECT VERSION(); args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.008) SHOW FULL TABLES; args=None
(0.006) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
(0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.000) SELECT VERSION(); args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.001) SELECT `users_userprofile`.`id`, `users_userprofile`.`password`, `users_userprofile`.`last_login`, `users_userprofile`.`is_superuser`, `users_userprofile`.`username`, `users_userprofile`.`first_name`, `users_userprofile`.`last_name`, `users_userprofile`.`is_staff`, `users_userprofile`.`is_active`, `users_userprofile`.`date_joined`, `users_userprofile`.`name`, `users_userprofile`.`birthday`, `users_userprofile`.`mobile`, `users_userprofile`.`gender`, `users_userprofile`.`email`, `users_userprofile`.`task_num` FROM `users_userprofile` WHERE (`users_userprofile`.`username` = 'admin' OR `users_userprofile`.`mobile` = 'admin'); args=('admin', 'admin')
"POST /login/ HTTP/1.1" 200 176
(0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.000) SELECT VERSION(); args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.001) SELECT `users_userprofile`.`id`, `users_userprofile`.`password`, `users_userprofile`.`last_login`, `users_userprofile`.`is_superuser`, `users_userprofile`.`username`, `users_userprofile`.`first_name`, `users_userprofile`.`last_name`, `users_userprofile`.`is_staff`, `users_userprofile`.`is_active`, `users_userprofile`.`date_joined`, `users_userprofile`.`name`, `users_userprofile`.`birthday`, `users_userprofile`.`mobile`, `users_userprofile`.`gender`, `users_userprofile`.`email`, `users_userprofile`.`task_num` FROM `users_userprofile` WHERE `users_userprofile`.`username` = 'admin'; args=('admin',)
(0.003) SELECT `tasks_taskinfo`.`id`, `tasks_taskinfo`.`user_id`, `tasks_taskinfo`.`task_name`, `tasks_taskinfo`.`data_num`, `tasks_taskinfo`.`status_type`, `tasks_taskinfo`.`add_time`, `tasks_taskinfo`.`task_desc`, `tasks_taskinfo`.`task_home`, `tasks_taskinfo`.`task_folder` FROM `tasks_taskinfo` WHERE `tasks_taskinfo`.`id` = 1; args=(1,)
data_set_name is /Users/cribbee/Downloads/1/Data/1261.json
(0.000) SELECT `tasks_taskinfo`.`id`, `tasks_taskinfo`.`user_id`, `tasks_taskinfo`.`task_name`, `tasks_taskinfo`.`data_num`, `tasks_taskinfo`.`status_type`, `tasks_taskinfo`.`add_time`, `tasks_taskinfo`.`task_desc`, `tasks_taskinfo`.`task_home`, `tasks_taskinfo`.`task_folder` FROM `tasks_taskinfo` WHERE `tasks_taskinfo`.`id` = 1; args=(1,)
(0.002) INSERT INTO `tasks_dataset` (`user_id`, `task_id`, `title`, `desc`, `x_axis`, `y_axis`, `chart_type`, `step1`, `step2`, `step3`, `step4`, `step5`, `add_time`) VALUES (2, 1, '', '', '', '', 0, '/Users/cribbee/Downloads/1/Data/1261.json', '/Users/cribbee/Downloads/1/Data/1262.csv', '/Users/cribbee/Downloads/1/Data/1263.csv', '', '', '2018-06-25 10:30:16.873482'); args=[2, 1, '', '', '', '', 0, '/Users/cribbee/Downloads/1/Data/1261.json', '/Users/cribbee/Downloads/1/Data/1262.csv', '/Users/cribbee/Downloads/1/Data/1263.csv', '', '', '2018-06-25 10:30:16.873482']
"POST /dataSet/ HTTP/1.1" 201 164
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/urls/resolvers.py", line 523, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLPattern '^upload/(?P<path>.*)$'>], [<URLResolver <module 'rest_framework.urls' from '/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/urls.py'> (rest_framework:rest_framework) '^api-auth/'>], [<URLResolver <module 'tasks.urls' from '/Users/cribbee/PycharmProjects/ZoomInDev/apps/tasks/urls.py'> (None:None) '^task'>, <URLPattern '^/getJsonFile$'>], [<URLResolver <module 'tasks.urls' from '/Users/cribbee/PycharmProjects/ZoomInDev/apps/tasks/urls.py'> (None:None) '^task'>, <URLPattern '^/dataProcessing$'>], [<URLResolver <module 'tasks.urls' from '/Users/cribbee/PycharmProjects/ZoomInDev/apps/tasks/urls.py'> (None:None) '^task'>, <URLPattern '^/scoreAnalysis$'>], [<URLResolver <module 'tasks.urls' from '/Users/cribbee/PycharmProjects/ZoomInDev/apps/tasks/urls.py'> (None:None) '^task'>, <URLPattern '^/dataProcessing/missingValue$'>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^users/$' [name='users-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^users\.(?P<format>[a-z0-9]+)/?$' [name='users-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask/$' [name='usertask-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask\.(?P<format>[a-z0-9]+)/?$' [name='usertask-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask/(?P<tasks_id>[^/.]+)/$' [name='usertask-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask/(?P<tasks_id>[^/.]+)\.(?P<format>[a-z0-9]+)/?$' [name='usertask-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo/$' [name='task-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo\.(?P<format>[a-z0-9]+)/?$' [name='task-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo/(?P<pk>[^/.]+)/$' [name='task-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo/(?P<pk>[^/.]+)\.(?P<format>[a-z0-9]+)/?$' [name='task-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet/$' [name='dataSet-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet\.(?P<format>[a-z0-9]+)/?$' [name='dataSet-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet/(?P<pk>[^/.]+)/$' [name='dataSet-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet/(?P<pk>[^/.]+)\.(?P<format>[a-z0-9]+)/?$' [name='dataSet-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^$' [name='api-root']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^\.(?P<format>[a-z0-9]+)/?$' [name='api-root']>], [<URLResolver <URLPattern list> (api-docs:api-docs) 'docs/'>], [<URLPattern '^api-token-auth/'>], [<URLPattern '^login/'>]], 'path': 'task/dataProcessing/missing_value'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'rest_framework.urls' from '/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/urls.py'> (rest_framework:rest_framework) '^api-auth/'>
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/urls/resolvers.py", line 523, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLPattern '^upload/(?P<path>.*)$'>], [<URLResolver <module 'rest_framework.urls' from '/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/urls.py'> (rest_framework:rest_framework) '^api-auth/'>], [<URLResolver <module 'tasks.urls' from '/Users/cribbee/PycharmProjects/ZoomInDev/apps/tasks/urls.py'> (None:None) '^task'>, <URLPattern '^/getJsonFile$'>], [<URLResolver <module 'tasks.urls' from '/Users/cribbee/PycharmProjects/ZoomInDev/apps/tasks/urls.py'> (None:None) '^task'>, <URLPattern '^/dataProcessing$'>], [<URLResolver <module 'tasks.urls' from '/Users/cribbee/PycharmProjects/ZoomInDev/apps/tasks/urls.py'> (None:None) '^task'>, <URLPattern '^/scoreAnalysis$'>], [<URLResolver <module 'tasks.urls' from '/Users/cribbee/PycharmProjects/ZoomInDev/apps/tasks/urls.py'> (None:None) '^task'>, <URLPattern '^/dataProcessing/missingValue$'>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^users/$' [name='users-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^users\.(?P<format>[a-z0-9]+)/?$' [name='users-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask/$' [name='usertask-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask\.(?P<format>[a-z0-9]+)/?$' [name='usertask-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask/(?P<tasks_id>[^/.]+)/$' [name='usertask-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^usertask/(?P<tasks_id>[^/.]+)\.(?P<format>[a-z0-9]+)/?$' [name='usertask-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo/$' [name='task-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo\.(?P<format>[a-z0-9]+)/?$' [name='task-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo/(?P<pk>[^/.]+)/$' [name='task-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^taskinfo/(?P<pk>[^/.]+)\.(?P<format>[a-z0-9]+)/?$' [name='task-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet/$' [name='dataSet-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet\.(?P<format>[a-z0-9]+)/?$' [name='dataSet-list']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet/(?P<pk>[^/.]+)/$' [name='dataSet-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^dataSet/(?P<pk>[^/.]+)\.(?P<format>[a-z0-9]+)/?$' [name='dataSet-detail']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^$' [name='api-root']>], [<URLResolver <URLPattern list> (None:None) '^'>, <URLPattern '^\.(?P<format>[a-z0-9]+)/?$' [name='api-root']>], [<URLResolver <URLPattern list> (api-docs:api-docs) 'docs/'>], [<URLPattern '^api-token-auth/'>], [<URLPattern '^login/'>]], 'path': 'task/dataProcessing/missing_value'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <URLPattern list> (api-docs:api-docs) 'docs/'>
Not Found: /task/dataProcessing/missing_value
"POST /task/dataProcessing/missing_value HTTP/1.1" 404 6409



Internal Server Error: /task/dataProcessing/missingValue
Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/request.py", line 411, in __getattr__
    return getattr(self._request, attr)
AttributeError: 'WSGIRequest' object has no attribute 'request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/cribbee/PycharmProjects/ZoomInDev/apps/tasks/views.py", line 178, in missing_value
    request = self.request
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/request.py", line 413, in __getattr__
    return self.__getattribute__(attr)
AttributeError: 'Request' object has no attribute 'request'
"POST /task/dataProcessing/missingValue HTTP/1.1" 500 16858
(0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.000) SELECT VERSION(); args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.027) SHOW FULL TABLES; args=None
(0.003) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
Internal Server Error: /task/dataProcessing/missingValue
Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/request.py", line 411, in __getattr__
    return getattr(self._request, attr)
AttributeError: 'WSGIRequest' object has no attribute 'request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/cribbee/PycharmProjects/ZoomInDev/apps/tasks/views.py", line 178, in missing_value
    request = self.request
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/request.py", line 413, in __getattr__
    return self.__getattribute__(attr)
AttributeError: 'Request' object has no attribute 'request'
"POST /task/dataProcessing/missingValue HTTP/1.1" 500 16858
Internal Server Error: /task/dataProcessing/missingValue
Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/request.py", line 411, in __getattr__
    return getattr(self._request, attr)
AttributeError: 'WSGIRequest' object has no attribute 'request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/cribbee/PycharmProjects/ZoomInDev/apps/tasks/views.py", line 178, in missing_value
    request = self.request
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/request.py", line 413, in __getattr__
    return self.__getattribute__(attr)
AttributeError: 'Request' object has no attribute 'request'
"POST /task/dataProcessing/missingValue HTTP/1.1" 500 16858
Internal Server Error: /task/dataProcessing/missingValue
Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/request.py", line 411, in __getattr__
    return getattr(self._request, attr)
AttributeError: 'WSGIRequest' object has no attribute 'request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/cribbee/PycharmProjects/ZoomInDev/apps/tasks/views.py", line 178, in missing_value
    request = self.request
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/request.py", line 413, in __getattr__
    return self.__getattribute__(attr)
AttributeError: 'Request' object has no attribute 'request'
"POST /task/dataProcessing/missingValue HTTP/1.1" 500 16858
(0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.000) SELECT VERSION(); args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.001) SHOW FULL TABLES; args=None
(0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
Internal Server Error: /task/dataProcessing/missingValue
Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/request.py", line 411, in __getattr__
    return getattr(self._request, attr)
AttributeError: 'WSGIRequest' object has no attribute 'request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/cribbee/PycharmProjects/ZoomInDev/apps/tasks/views.py", line 178, in missing_value
    request = self.request
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/request.py", line 413, in __getattr__
    return self.__getattribute__(attr)
AttributeError: 'Request' object has no attribute 'request'
"POST /task/dataProcessing/missingValue HTTP/1.1" 500 16858
Internal Server Error: /task/dataProcessing/missingValue
Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/request.py", line 411, in __getattr__
    return getattr(self._request, attr)
AttributeError: 'WSGIRequest' object has no attribute 'request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/cribbee/PycharmProjects/ZoomInDev/apps/tasks/views.py", line 178, in missing_value
    request = self.request
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/request.py", line 413, in __getattr__
    return self.__getattribute__(attr)
AttributeError: 'Request' object has no attribute 'request'
"POST /task/dataProcessing/missingValue HTTP/1.1" 500 16858
(0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.000) SELECT VERSION(); args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.024) SHOW FULL TABLES; args=None
(0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
Internal Server Error: /task/dataProcessing/missingValue
Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/request.py", line 411, in __getattr__
    return getattr(self._request, attr)
AttributeError: 'WSGIRequest' object has no attribute 'request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/cribbee/PycharmProjects/ZoomInDev/apps/tasks/views.py", line 178, in missing_value
    req = self.request
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/request.py", line 413, in __getattr__
    return self.__getattribute__(attr)
AttributeError: 'Request' object has no attribute 'request'
"POST /task/dataProcessing/missingValue HTTP/1.1" 500 16854
Internal Server Error: /task/dataProcessing/missingValue
Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/request.py", line 411, in __getattr__
    return getattr(self._request, attr)
AttributeError: 'WSGIRequest' object has no attribute 'request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/cribbee/PycharmProjects/ZoomInDev/apps/tasks/views.py", line 178, in missing_value
    req = self.request
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/request.py", line 413, in __getattr__
    return self.__getattribute__(attr)
AttributeError: 'Request' object has no attribute 'request'
"POST /task/dataProcessing/missingValue HTTP/1.1" 500 16854
Internal Server Error: /task/dataProcessing/missingValue
Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/request.py", line 411, in __getattr__
    return getattr(self._request, attr)
AttributeError: 'WSGIRequest' object has no attribute 'request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/cribbee/PycharmProjects/ZoomInDev/apps/tasks/views.py", line 178, in missing_value
    req = self.request
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/request.py", line 413, in __getattr__
    return self.__getattribute__(attr)
AttributeError: 'Request' object has no attribute 'request'
"POST /task/dataProcessing/missingValue HTTP/1.1" 500 16854
(0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.000) SELECT VERSION(); args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.010) SHOW FULL TABLES; args=None
(0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
"POST /task/dataProcessing/missingValue HTTP/1.1" 415 77
(0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.000) SELECT VERSION(); args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.002) SELECT `tasks_dataset`.`id`, `tasks_dataset`.`user_id`, `tasks_dataset`.`task_id`, `tasks_dataset`.`title`, `tasks_dataset`.`desc`, `tasks_dataset`.`x_axis`, `tasks_dataset`.`y_axis`, `tasks_dataset`.`chart_type`, `tasks_dataset`.`step1`, `tasks_dataset`.`step2`, `tasks_dataset`.`step3`, `tasks_dataset`.`step4`, `tasks_dataset`.`step5`, `tasks_dataset`.`add_time` FROM `tasks_dataset` WHERE `tasks_dataset`.`id` = 4; args=(4,)
Internal Server Error: /task/dataProcessing/missingValue
Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/cribbee/PycharmProjects/ZoomInDev/apps/tasks/views.py", line 176, in missing_value
    how=request.data['how'], thresh=request.data['thresh'])
  File "/Users/cribbee/PycharmProjects/ZoomInDev/db_tools/dataProcessing.py", line 53, in missing_value
    dfd = df.dropna(axis=axis, how=how, thresh=thresh)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/pandas/core/frame.py", line 4288, in dropna
    mask = count >= thresh
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/pandas/core/ops.py", line 1253, in wrapper
    res = na_op(values, other)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/pandas/core/ops.py", line 1166, in na_op
    raise TypeError("invalid type comparison")
TypeError: invalid type comparison
"POST /task/dataProcessing/missingValue HTTP/1.1" 500 17071
"POST /task/dataProcessing/missingValue HTTP/1.1" 400 75
(0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.000) SELECT VERSION(); args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.005) SELECT `tasks_dataset`.`id`, `tasks_dataset`.`user_id`, `tasks_dataset`.`task_id`, `tasks_dataset`.`title`, `tasks_dataset`.`desc`, `tasks_dataset`.`x_axis`, `tasks_dataset`.`y_axis`, `tasks_dataset`.`chart_type`, `tasks_dataset`.`step1`, `tasks_dataset`.`step2`, `tasks_dataset`.`step3`, `tasks_dataset`.`step4`, `tasks_dataset`.`step5`, `tasks_dataset`.`add_time` FROM `tasks_dataset` WHERE `tasks_dataset`.`id` = 4; args=(4,)
Internal Server Error: /task/dataProcessing/missingValue
Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/cribbee/PycharmProjects/ZoomInDev/apps/tasks/views.py", line 176, in missing_value
    how=request.data['how'], thresh=request.data['thresh'])
  File "/Users/cribbee/PycharmProjects/ZoomInDev/db_tools/dataProcessing.py", line 53, in missing_value
    dfd = df.dropna(axis=axis, how=how, thresh=thresh)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/pandas/core/frame.py", line 4288, in dropna
    mask = count >= thresh
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/pandas/core/ops.py", line 1253, in wrapper
    res = na_op(values, other)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/pandas/core/ops.py", line 1166, in na_op
    raise TypeError("invalid type comparison")
TypeError: invalid type comparison
"POST /task/dataProcessing/missingValue HTTP/1.1" 500 17071
"POST /task/dataProcessing/missingValue HTTP/1.1" 400 75
(0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.000) SELECT VERSION(); args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.019) SHOW FULL TABLES; args=None
(0.004) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
(0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.000) SELECT VERSION(); args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.000) SELECT `tasks_dataset`.`id`, `tasks_dataset`.`user_id`, `tasks_dataset`.`task_id`, `tasks_dataset`.`title`, `tasks_dataset`.`desc`, `tasks_dataset`.`x_axis`, `tasks_dataset`.`y_axis`, `tasks_dataset`.`chart_type`, `tasks_dataset`.`step1`, `tasks_dataset`.`step2`, `tasks_dataset`.`step3`, `tasks_dataset`.`step4`, `tasks_dataset`.`step5`, `tasks_dataset`.`add_time` FROM `tasks_dataset` WHERE `tasks_dataset`.`id` = 4; args=(4,)
Internal Server Error: /task/dataProcessing/missingValue
Traceback (most recent call last):
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/cribbee/PycharmProjects/ZoomInDev/apps/tasks/views.py", line 175, in missing_value
    dataProcessing.process(open_path=data_set.step2).missing_value(axis=request.data['axis'], how=request.data['how'])
  File "/Users/cribbee/PycharmProjects/ZoomInDev/db_tools/dataProcessing.py", line 54, in missing_value
    dfd.to_csv("m"+self.open_path)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/pandas/core/frame.py", line 1745, in to_csv
    formatter.save()
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/pandas/io/formats/csvs.py", line 136, in save
    compression=None)
  File "/Users/cribbee/Virtualenv/V-ZoomIn/lib/python3.6/site-packages/pandas/io/common.py", line 400, in _get_handle
    f = open(path_or_buf, mode, encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'm/Users/cribbee/Downloads/1/Data/1262.csv'
"POST /task/dataProcessing/missingValue HTTP/1.1" 500 17177
(0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.000) SELECT VERSION(); args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.017) SHOW FULL TABLES; args=None
(0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
(0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.000) SELECT VERSION(); args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.000) SELECT `tasks_dataset`.`id`, `tasks_dataset`.`user_id`, `tasks_dataset`.`task_id`, `tasks_dataset`.`title`, `tasks_dataset`.`desc`, `tasks_dataset`.`x_axis`, `tasks_dataset`.`y_axis`, `tasks_dataset`.`chart_type`, `tasks_dataset`.`step1`, `tasks_dataset`.`step2`, `tasks_dataset`.`step3`, `tasks_dataset`.`step4`, `tasks_dataset`.`step5`, `tasks_dataset`.`add_time` FROM `tasks_dataset` WHERE `tasks_dataset`.`id` = 4; args=(4,)
(0.002) UPDATE `tasks_dataset` SET `user_id` = 2, `task_id` = 1, `title` = '', `desc` = '', `x_axis` = '', `y_axis` = '', `chart_type` = 0, `step1` = '/Users/cribbee/Downloads/1/Data/1261.json', `step2` = '/Users/cribbee/Downloads/1/Data/1262.csv', `step3` = '/Users/cribbee/Downloads/1/Data/1263m.csv', `step4` = '', `step5` = '', `add_time` = '2018-06-25 10:30:16.873482' WHERE `tasks_dataset`.`id` = 4; args=(2, 1, '', '', '', '', 0, '/Users/cribbee/Downloads/1/Data/1261.json', '/Users/cribbee/Downloads/1/Data/1262.csv', '/Users/cribbee/Downloads/1/Data/1263m.csv', '', '', '2018-06-25 10:30:16.873482', 4)
"POST /task/dataProcessing/missingValue HTTP/1.1" 200 38
"GET /docs/ HTTP/1.1" 200 127588
"GET /docs/schema.js HTTP/1.1" 200 10552
"GET /static/rest_framework/docs/img/favicon.ico HTTP/1.1" 200 5430
(0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.000) SELECT VERSION(); args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.011) SHOW FULL TABLES; args=None
(0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
(0.009) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.005) SELECT VERSION(); args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.066) SHOW FULL TABLES; args=None
(0.045) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
"GET / HTTP/1.1" 200 5617
"GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
"GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
"GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
"GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 304 0
"GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
"GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
"GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
"GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
"GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
"GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
